### ISSUE TITLE
emacs-rc-misc-things.el encodig 

### ISSUE THREAD

**Issue by holub** [alexott/emacs-configs#1]
Encoding of the file emacs-rc-misc-things.el (?UTF-16) isn't readable through the web interface:
http://github.com/alexott/emacs-configs/blob/0a6faf021b22c9f63d47ed0ba0a2f0b64374adb9/rc/emacs-rc-misc-things.el

**Comment by holub** [comment]
as well as http://github.com/alexott/emacs-configs/blob/0a6faf021b22c9f63d47ed0ba0a2f0b64374adb9/rc/emacs-rc-osd.el

**Comment by alexott** [comment]
fixed
