### ISSUE TITLE
filename from org-remember-templates is ignored

### ISSUE THREAD

**Issue by ysae** [alexott/emacs-configs#2]
File: https://github.com/alexott/emacs-configs/blob/master/rc/emacs-rc-org-mode.el#L77

<pre>(setq org-remember-templates
      '(
        ("Todo" ?t "* TODO %?\n %i\n %a" (concat org-directory "/TODO.org") "Tasks")
        ))</pre>

Filename TODO.org ignored in template selection (C-r) while using 'concat' in filename construction.
Data will be stored in the org-default-notes-file (notes.org).

But it's OK for string with explicit filename:

<pre>(setq org-remember-templates
      '(
        ("Todo" ?t "* TODO %?\n %i\n %a" ""~/projects/OrgMode/TODO.org" "Tasks")
        ))</pre>

emacs23.2, org-mode7.5

**Comment by alexott** [comment]
Ok, thanks. I remember that it worked for me long time ago, but I don't use this functionality very often.
