### ISSUE TITLE
coding issues when opening shell 

### ISSUE THREAD

**Issue by zinking** [alexott/emacs-configs#5]
I was using cygwin emacs with your configuration , commented out some section

so I encountered the weird codings 
$ lsll
bash: lsll: команда не найдена

something like Russia coding, if I remove the configuration totally, then everything is fine, is there some configuration that is setting the language to Russian ?

**Comment by alexott** [comment]
look into https://github.com/alexott/emacs-configs/blob/master/rc/emacs-rc-mule.el#L21 - it explicitly sets the LANG (I think, that this is an artifact of some old workaround...)
